import React from 'react';
import { Document, Page, Text, View, StyleSheet, Image, Font } from '@react-pdf/renderer';

// Register fonts if needed, but standard ones are faster for now
// Font.register({ family: 'Hind Siliguri', src: '...' });

const styles = StyleSheet.create({
    page: {
        padding: 40,
        fontFamily: 'Helvetica',
        backgroundColor: '#FFFFFF',
    },
    header: {
        marginBottom: 20,
        borderBottom: 1,
        borderBottomColor: '#E5E5E5',
        paddingBottom: 10,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#0A0A0A',
    },
    subtitle: {
        fontSize: 10,
        color: '#666666',
        marginTop: 4,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    messageContainer: {
        marginBottom: 15,
        padding: 10,
        borderRadius: 5,
    },
    userMessage: {
        backgroundColor: '#F3F4F6',
        alignSelf: 'flex-end',
        maxWidth: '80%',
    },
    assistantMessage: {
        backgroundColor: '#FFFFFF',
        borderLeft: 3,
        borderLeftColor: '#0A0A0A',
        maxWidth: '90%',
    },
    role: {
        fontSize: 8,
        fontWeight: 'bold',
        marginBottom: 4,
        color: '#9CA3AF',
        textTransform: 'uppercase',
    },
    content: {
        fontSize: 11,
        lineHeight: 1.5,
        color: '#1F2937',
    },
    image: {
        marginTop: 10,
        borderRadius: 5,
        width: '100%',
        maxHeight: 250,
        objectFit: 'cover',
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 40,
        right: 40,
        textAlign: 'center',
        fontSize: 8,
        color: '#9CA3AF',
        borderTop: 0.5,
        borderTopColor: '#E5E5E5',
        paddingTop: 10,
    }
});

interface Message {
    role: 'user' | 'assistant';
    content: string;
    toolInvocations?: any[];
}

export const ChatPDF = ({ messages, userName }: { messages: Message[], userName: string }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                <Text style={styles.title}>Construction Consultation</Text>
                <Text style={styles.subtitle}>Generated by Dalankotha AI • Prepared for {userName}</Text>
            </View>

            {messages.map((msg, index) => (
                <View key={index} style={[
                    styles.messageContainer,
                    msg.role === 'user' ? styles.userMessage : styles.assistantMessage
                ]}>
                    <Text style={styles.role}>{msg.role === 'user' ? 'You' : 'Dalankotha AI Consultant'}</Text>
                    <Text style={styles.content}>{msg.content}</Text>

                    {msg.toolInvocations?.map((tool, tIdx) => (
                        tool.state === 'result' && tool.result?.url && (
                            <Image key={tIdx} src={tool.result.url} style={styles.image} />
                        )
                    ))}
                </View>
            ))}

            <Text style={styles.footer}>
                This document is an AI-generated consultation. Please verify structural details with a certified professional.
                Visit www.Dalankotha.com.bd for more details.
            </Text>
        </Page>
    </Document>
);
